### PR TITLE
feat/combined_output

### PR DESCRIPTION
**Pull request by builderjer**
This should enable all audio outputs to be combined.

### CODE REVIEW

**Comment by j1nx** [comment]
This needs some proper testing for hdmi use cases.

the hdmi interfaces use ac97 digital audio, so in case of hdmi and 3,5 jack combined a lot of up and down resampling is happening causing stuttered and/ or bad playback.

i do however not have a solution or alternative yet.

A proper VUI to select the default output might be the best solution however again, no proper idea about how to do it as well.

**Comment by JarbasAl** [comment]
Does this apply to pipe wire? The images do not use pulseaudio

**Comment by builderjer** [comment]
Yes, this should be good for pipewire.

Testing I can understand, but this is the file that I use with all of my setups and it seems to work.  Even the one with a HDMI output.  I do not however have a 3.5mm out running.

A VUI would be great, but not for a headless device

**Comment by j1nx** [comment]
> Yes, this should be good for pipewire.
> 
> Testing I can understand, but this is the file that I use with all of my setups and it seems to work. Even the one with a HDMI output. I do not however have a 3.5mm out running.
> 
> A VUI would be great, but not for a headless device

Voice User Interface 🤪

**Comment by JarbasAl** [comment]
here is a build (without OVOS, just the base OS) for testing this PR https://github.com/OpenVoiceOS/raspOVOS/releases/tag/raspOVOS-NO-OVOS-bookworm-arm64-lite-2024-12-26

**Pull request merged**
